formatter: 'markdown table'

version: ''

header-from: main.tf
footer-from: ''

recursive:
  enabled: false

sections:
  hide: []
  show: []

content: |-
  {{ .Header }}
  ## Special Inputs

  Following input variables will be set with automations. You do not have to set them in any `tfvars` file.

  1. `environment`
  1. `namespace`
  1. `region` - Only required to initialize the `aws` provider if it is not explicitly listed for the module inputs.
  1. `repo_id`
  1. `state_bucket`
  1. `state_key`

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ''

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: false
  indent: 2
  lockfile: true
  read-comments: true
  required: false
  sensitive: true
  type: true
